-- Add migration script here
-- Criação da tabela UF
CREATE TABLE IF NOT EXISTS uf (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR(2) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL
);

-- Criação da tabela Município
CREATE TABLE IF NOT EXISTS municipio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    uf_id BIGINT NOT NULL REFERENCES uf(id) ON DELETE CASCADE
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_municipio_nome ON municipio(nome);
CREATE INDEX IF NOT EXISTS idx_municipio_uf_id ON municipio(uf_id);
