-- Add migration script here
-- DROP TABLE IF EXISTS roles;

CREATE TABLE IF NOT EXISTS roles
(
    --id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id SERIAL PRIMARY KEY,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT core_role_name_key UNIQUE (name)
)