-- Add migration script here

CREATE TABLE IF NOT EXISTS chamado_tipos_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS chamado_servico_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    tipo_id BIGINT NOT NULL REFERENCES chamado_tipos_chamado(id),
    CONSTRAINT uq_servico_tipo_nome UNIQUE (tipo_id, nome)
);

CREATE TABLE IF NOT EXISTS chamado_categoria_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS chamado_chamados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    user_solic_id BIGINT NOT NULL REFERENCES users(id),
    servico_id BIGINT NOT NULL REFERENCES chamado_servico_chamado(id),
    tipo_id BIGINT NOT NULL REFERENCES chamado_tipos_chamado(id)
);

CREATE TABLE IF NOT EXISTS chamado_gerenciamento_chamado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    categoria_id BIGINT,
    chamado_id BIGINT NOT NULL,
    user_atend_id BIGINT NOT NULL,
    observacao_chamado TEXT,

    CONSTRAINT uq_gerenciamento_chamado_id UNIQUE (chamado_id),

    CONSTRAINT fk_gerenciamento_user FOREIGN KEY (user_atend_id)
        REFERENCES users(id),

    CONSTRAINT fk_gerenciamento_categoria FOREIGN KEY (categoria_id)
        REFERENCES chamado_categoria_chamado(id),

    CONSTRAINT fk_gerenciamento_chamado FOREIGN KEY (chamado_id)
        REFERENCES chamado_chamados(id)
);

-- Índices adicionais
CREATE INDEX IF NOT EXISTS idx_servico_tipo_id
    ON chamado_servico_chamado (tipo_id);

CREATE INDEX IF NOT EXISTS idx_tipos_chamado_nome
    ON chamado_tipos_chamado (nome);

CREATE INDEX IF NOT EXISTS idx_categoria_chamado_nome
    ON chamado_categoria_chamado (nome);
