[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
blog = {path="../blog"}
axum = "0.8"
tokio = { version = "1.47", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tower-http = { version = "0.6", features = ["trace", "metrics", "fs"] }
prometheus = "0.13"
minijinja = { version = "2.11", features = ["loader"] }
dotenv = "0.15"