[package]
name = "permissao"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
minijinja = { version = "2.11", features = ["loader"] }
axum = "0.8"
chrono = "0.4"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "macros", "chrono", "uuid"] }